package com.algorithmic_alliance.eyeaiapp.UI.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF4B5C92)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDBE1FF)
val OnPrimaryContainerLight = Color(0xFF334478)
val SecondaryLight = Color(0xFF595E72)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFDDE1F9)
val OnSecondaryContainerLight = Color(0xFF414659)
val TertiaryLight = Color(0xFF745470)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFD6F8)
val OnTertiaryContainerLight = Color(0xFF5B3D58)
val BackgroundLight = Color(0xFFFAF8FF)
val OnBackgroundLight = Color(0xFF1A1B21)
val SurfaceLight = Color(0xFFFAF8FF)
val OnSurfaceLight = Color(0xFF1A1B21)
val SurfaceVariantLight = Color(0xFFE2E2EC)
val OnSurfaceVariantLight = Color(0xFF45464F)
val OutlineLight = Color(0xFF757680)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)

val PrimaryDark = Color(0xFFB4C5FF)
val OnPrimaryDark = Color(0xFF1B2D60)
val PrimaryContainerDark = Color(0xFF334478)
val OnPrimaryContainerDark = Color(0xFFDBE1FF)
val SecondaryDark = Color(0xFFC1C5DD)
val OnSecondaryDark = Color(0xFF2B3042)
val SecondaryContainerDark = Color(0xFF414659)
val OnSecondaryContainerDark = Color(0xFFDDE1F9)
val TertiaryDark = Color(0xFFE2BBDB)
val OnTertiaryDark = Color(0xFF422740)
val TertiaryContainerDark = Color(0xFF5B3D58)
val OnTertiaryContainerDark = Color(0xFFFFD6F8)
val BackgroundDark = Color(0xFF121318)
val OnBackgroundDark = Color(0xFFE3E2E9)
val SurfaceDark = Color(0xFF121318)
val OnSurfaceDark = Color(0xFFE3E2E9)
val SurfaceVariantDark = Color(0xFF45464F)
val OnSurfaceVariantDark = Color(0xFFC5C6D0)
val OutlineDark = Color(0xFF8F909A)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
